### ISSUE TITLE
Connect reg_vars to svy_analysis

### ISSUE THREAD

**Issue by jwbowers** [bowers-illinois-edu/zomba-design#10]
The first  few lines of  `selecetvars.Rmd` fail because  the covariates (And some outcomes  are  not  in the dataset):

```
> covdat1 <- svy_analysis[,covs]
Error in `[.data.frame`(svy_analysis, , covs) : 
  undefined columns selected
> covdat2 <- svy_analysis  %>% dplyr::select(one_of(covs))
Warning message:
Unknown columns: `female`, `age`, `education`, `income_month`, `house_size`, `service_cw`, `part_cw`, `benefit_formalize_survey_b`, `cohesion_cw`, `ses_cw` 
```

**Comment by lulachen** [comment]
I edited reg_vars.rda and just ran selectvars.Rmd.  It seems to work now.  The unknown columns needed a "_b" because we want the covariates from baseline.  `tax_compliance_admin_e` should have been `taxcompliance_admin_e`

**Comment by jwbowers** [comment]
So: `_b` means "baseline"? What does `_e` mean? Thanks!

**Comment by lulachen** [comment]
`_e` means endline.

**Comment by jwbowers** [comment]
Great.  Thanks!
