### ISSUE TITLE
Crime and Contribute

### ISSUE THREAD

**Issue by jwbowers** [bowers-illinois-edu/zomba-design#11]
Found this:
```
> table(covdat$crime.NA,covdat$contribute.NA,exclude=c())
       
        FALSE TRUE
  FALSE  1854    0
  TRUE      0    1
```
Seems like we don't need both covariates. Also,  I'm a  bit  confused why we  have `crime.NA` and  `contribute.NA` but not `crime` and  `contribute`.  Explanation?

**Comment by jwbowers** [comment]
See also:

```
> table(covdat$ses_6.NA,covdat$ses_5.NA,exclude=c())
       
        FALSE TRUE
  FALSE  1853    0
  TRUE      0    2
```

**Comment by jwbowers** [comment]
I'm tempted to dump both contribute.NA and crime.NA as well as the ses_5  and ses_6 variables. They are  so sparse that hard to imagine them providing much explanatory power.

**Comment by lulachen** [comment]
Ok. ses_cw is also a covariance-weighted index of the SES variables.

**Comment by cdgrady21** [comment]
And "crime" and "contribute" are components of the cohesion index.  We did not include the components of the index as variables, but we included the ".NA" versions of the components.

**Comment by jwbowers** [comment]
Great. Done.
