### ISSUE TITLE
Guidance on coding on taxmorale_survey_e

### ISSUE THREAD

**Issue by jwbowers** [bowers-illinois-edu/zomba-design#13]
Do we keep the -2 and -1 in this variable? Or are they also missing?

```
$taxmorale_survey_e

  -2   -1    1    2 <NA> 
 843  144   90  495  283 
```

**Comment by lulachen** [comment]
-2 and -1 are measurements for this variable.  EGAP wanted the following: 

- -2 Very strong prefer "Citizens should only pay their taxes if they agree with the government or its actions", 
- -1 Not very strong prefer "Citizens should only pay their taxes if they agree with the government or its actions", 
- 1 Not very strong prefer "Citizens should always pay their taxes even if they disagree with the government or its actions", 
- 2 Very strong prefer "Citizens should always pay their taxes even if they disagree with the government or its actions"

**Comment by jwbowers** [comment]
Great.
