### ISSUE TITLE
No variation within control group on a covariate?

### ISSUE THREAD

**Issue by jwbowers** [bowers-illinois-edu/zomba-design#15]
This covariate will not help us since it has no variation in the control condition (Which is also funny given the sample size of this experiment).  I propose to remove this covariate from the analysis until we figure out what is going on.

```
> table(svy_analysis$info_issue,svy_analysis$Z,exclude=c())
   
       0    1
  0 1021  774
  1    0   60
> 
```

This pattern holds even when we take out the pure control blocks:

```
> table(wrkdat$info_issue,wrkdat$Z,exclude=c())
   
      0   1
  0 835 774
  1   0  60

```

**Comment by lulachen** [comment]
Yes, that makes sense.  The variable `info_issue` is an indicator for the canvassers who were negative to the households who received the brochure.

**Comment by jwbowers** [comment]
Closing this. Also excluding access_publicse_survey_b.NA as having no variation within the control group.
